### ISSUE TITLE
Allow specifying rooms to be served as CLI arguments

### ISSUE THREAD

**Issue by wyqydsyq** [curtiswilkinson/zoey-cli#20]
It would be nice to be able to specify a room if you only want to run roomservice for that particular room

e.g. you just pulled develop and want to test out a single service, but don't want to wait for services irrelevant to your task to rebuild if they've also had changes

This would allow us to completely replace our build bash scripts (redock in this case) with roomservice

It might even be ideal to parse every argument after the options as target rooms, so users could also specify a list of rooms to build, if no rooms are specified just behave like now and build everything in the config file

**Comment by curtiswilkinson** [comment]
100% agree, I'm currently spiking a re-write into ReasonML with a different architecture that makes this much easier

I'll definitely add it to the feature set

**Comment by curtiswilkinson** [comment]
This was released in `3.0.3` 🎈
