### ISSUE TITLE
Output formatting - Friday afternoon nitpicking

### ISSUE THREAD

**Issue by foxdb** [curtiswilkinson/zoey-cli#4]
Mostly suggestions

- [x] `Just servicing your rooms: X,Y` is formatted like `Just servicing your rooms: X, Y` There's no more space missing between the comma and the next service

- [x] Had changes in two of my services, one of them got listed twice after the `Looks like these changed so I built them for you: ` announcement.

- [x] Two seconds before first output after typing `roomservice`, I thought it was stuck, but in fact it did everything I expected it to do! Maybe you could output something to let the user know that it's happening

- [x] Could I see the total build time at the end? From the moment I pressed enter to the final output?

**Comment by curtiswilkinson** [comment]
All of the fixes above are released in `1.1.0` 🎈 🎉 🥐
